service: aws-go-http-api-project
frameworkVersion: "3"

provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: go1.x

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  fetchUsers:
    handler: bin/fetch-users
    events:
      - httpApi:
          path: /
          method: get
  createUser:
    handler: bin/create-user
    events:
      - httpApi:
          path: /
          method: post
